# Generated by Django 4.2 on 2024-02-20 14:10

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtítulo')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(default='Texto', verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='news', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'anuncios',
                'verbose_name_plural': 'anuncios',
                'ordering': ['-created'],
            },
        ),
    ]
