# Generated by Django 4.2 on 2024-03-07 03:49

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtítulo')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(default='Texto', verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='anuncion_evenet', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Curiosidad',
                'verbose_name_plural': 'Curiosidades',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(default='Texto', verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='Contenido', verbose_name='Imagen')),
                ('fecha_event', models.DateTimeField(null=True, verbose_name='Fecha del evento')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
