# Generated by Django 3.2.25 on 2024-05-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_content_event_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='curio',
            table='curiosidades',
        ),
        migrations.AlterModelTable(
            name='event',
            table='eventos',
        ),
    ]
