# Generated by Django 4.2.8 on 2024-05-07 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 16, 35, 7, 886043, tzinfo=datetime.timezone.utc)),
        ),
    ]
