# Generated by Django 4.2.8 on 2024-05-09 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 4, 33, 5, 430898, tzinfo=datetime.timezone.utc)),
        ),
    ]
