# Generated by Django 3.2.5 on 2024-09-21 03:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 3, 9, 32, 368903, tzinfo=utc)),
        ),
    ]
