# Generated by Django 3.2.5 on 2024-10-28 02:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 2, 34, 38, 932700, tzinfo=utc)),
        ),
    ]
