# Generated by Django 3.2.5 on 2024-10-31 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='curio',
            name='activo',
            field=models.BooleanField(default=True, null=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 31, 15, 10, 35, 332848, tzinfo=utc)),
        ),
    ]
