# Generated by Django 4.2.17 on 2025-01-14 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20241031_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enlace',
            field=models.URLField(null=True, verbose_name='Enlace a las redes'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 14, 4, 2, 22, 480880, tzinfo=datetime.timezone.utc)),
        ),
    ]
