# Generated by Django 4.2.17 on 2025-01-26 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_event_enlace_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 4, 46, 8, 227607, tzinfo=datetime.timezone.utc)),
        ),
    ]
