# Generated by Django 4.2.17 on 2025-01-28 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 3, 19, 44, 587631, tzinfo=datetime.timezone.utc)),
        ),
    ]
