# Generated by Django 4.2.17 on 2025-02-11 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 3, 11, 49, 257950, tzinfo=datetime.timezone.utc)),
        ),
    ]
