# Generated by Django 4.2.17 on 2025-02-12 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 3, 25, 48, 726156, tzinfo=datetime.timezone.utc)),
        ),
    ]
