# Generated by Django 3.2.5 on 2024-10-28 02:34

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellidos', models.CharField(max_length=200, verbose_name='Nombre y apellidos')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(default=' ', verbose_name='Reseña')),
                ('foto', models.ImageField(default='equipo/generico.png', null=True, upload_to='equipo', verbose_name='Foto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'equipo',
                'ordering': ['-created'],
            },
        ),
    ]
