# Generated by Django 3.2.5 on 2024-10-31 15:10

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(default=' ', null=True, verbose_name='Reseña'),
        ),
    ]
