# Generated by Django 4.2.17 on 2025-01-28 03:19

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_alter_miembro_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(default=' ', null=True, verbose_name='Reseña')),
                ('foto', models.ImageField(default='equipo/generico.png', null=True, upload_to='equipo', verbose_name='Foto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'tienda',
                'verbose_name_plural': 'Tienda',
                'db_table': 'tienda',
                'ordering': ['-created'],
            },
        ),
    ]
