# Generated by Django 4.2 on 2024-02-20 02:30

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Texto', verbose_name='Contenido'),
        ),
    ]
