# Generated by Django 4.2 on 2024-03-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_pagina_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre')),
                ('image', models.ImageField(storage='media/banner', upload_to='', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['created'],
            },
        ),
    ]
