# Generated by Django 4.2 on 2024-03-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_banner_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners', verbose_name='Imagen'),
        ),
    ]
