# Generated by Django 4.2.8 on 2024-03-19 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_banner_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='banner',
        ),
    ]
