# Generated by Django 3.2.25 on 2024-05-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagina',
            new_name='Paginas',
        ),
        migrations.AlterModelTable(
            name='paginas',
            table='paginas',
        ),
    ]
