# Generated by Django 3.2 on 2025-03-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='correo',
            field=models.CharField(max_length=10, null='True', verbose_name='Correo electrónico'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(max_length=10, null='True', verbose_name='Teléfono (Con WhatsApp)'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='usuario',
            field=models.CharField(max_length=100, verbose_name='Nombre y apellidos'),
        ),
    ]
