# Generated by Django 3.2.25 on 2024-05-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enlac_preg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enlaces',
            table='enlace',
        ),
        migrations.AlterModelTable(
            name='pregunta',
            table='pregunta',
        ),
    ]
