# Generated by Django 4.2 on 2024-03-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='is_product',
            field=models.BooleanField(blank=True, null=True, verbose_name='Para la sección productos'),
        ),
    ]
