# Generated by Django 3.2.25 on 2024-05-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_imagenes_is_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='banner',
        ),
    ]
