# Generated by Django 3.2.25 on 2024-05-03 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_banner_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='is_product',
        ),
    ]
