# Generated by Django 3.2.25 on 2024-05-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_remove_imagenes_is_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagenes',
            table='imagenes',
        ),
    ]
