# Generated by Django 3.2.5 on 2024-09-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_imagenes_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='pcpal',
            field=models.BooleanField(default=False),
        ),
    ]
