# Generated by Django 4.2.17 on 2025-01-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_carrusel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='image',
            field=models.ImageField(upload_to='galeria_1', verbose_name='Imagen'),
        ),
    ]
