# Generated by Django 4.2.17 on 2025-02-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_alter_carrusel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='is_princ',
            field=models.BooleanField(blank=True, null=True, verbose_name='Principal'),
        ),
    ]
