# Generated by Django 4.2.17 on 2025-02-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_imagenes_is_princ'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='enlace',
            field=models.URLField(null=True, verbose_name='Enlace a las redes'),
        ),
    ]
