# Generated by Django 4.2.17 on 2025-02-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_banner_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='enlace',
            field=models.URLField(default='https://produccionesmuhia.ca', verbose_name='Enlace a las redes'),
        ),
    ]
